### ISSUE TITLE
After update to new image with MariaDB 10.3.12 no connection possible

### ISSUE THREAD

**Issue by BudBundi** [yobasystems/alpine-mariadb#24]
Because the logs, I overlooked the bigger problem, container is not reachable from the outside.
I also try to create a new database  but the container refuse all connections, so I see in the logs: 

`Version: '10.3.12-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server`

The port is wrong, maybe a wrong default configuration?

**Comment by HoiPangCHEUNG** [comment]
Encountered the same problem, see the following error msg for reference

time="2019-02-12T09:40:38Z" level=fatal msg="dial tcp 172.24.0.1:3306: connect: connection refused"
-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by dominictayloruk** [comment]
Thats because Mariadb connects using the socket protocol.

## PROTOCOL

Specifies the protocol to be used for the connection for the connection. It can be one of TCP, SOCKET, PIPE or MEMORY (case-insensitive). Usually you would not want to change this from the default. For example on Unix, a Unix socket file (SOCKET) is the default protocol, and usually results in the quickest connection.

* TCP: A TCP/IP connection to a server (either local or remote). Available on all operating systems.
* SOCKET: A Unix socket file connection, available to the local server on Unix systems only.
* PIPE. A named-pipe connection (either local or remote). Available on Windows only.
* MEMORY. Shared-memory connection to the local server on Windows systems only.

More info https://mariadb.com/kb/en/library/connecting-to-mariadb/

**Comment by dominictayloruk** [comment]
Actually your right, i've just checked on the previous build

`Version: '10.2.19-MariaDB-log'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server`

`Version: '10.3.12-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 0  MariaDB Server`

**Comment by whalevillage** [comment]
Using option: --skip-networking=0 --bind-address=0 -P3306 
solves the issue for me.

**Comment by KingRial** [comment]
I just fixed my current docker compose script by:
- Copying a script which fixes the configuration:
```
COPY ./check.sh /scripts/pre-exec.d
```
- Where "check.sh" is:
```
#Adding comment to configuration:
sed -i.bak s/^skip-networking/\#skip-networking/g /etc/my.cnf.d/mariadb-server.cnf
```

**Comment by dominictayloruk** [comment]
Should be fixed in https://github.com/yobasystems/alpine-mariadb/commit/19cab7832101152cd4cbee71e923229646d7cf12

**Comment by dominictayloruk** [comment]
Fixed in the latest version

`Version: '10.3.12-MariaDB'  socket: '/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server`
