### ISSUE TITLE
add support for galera

### ISSUE THREAD

**Issue by netwrkx** [yobasystems/alpine-mariadb#56]

**Comment by dominictayloruk** [comment]
Feel free to submit a pull request. 

I think all that is required would be to build the Galera wsrep provider library package, as everything else should be baked into the standard mariadb package. 

There is a package for amd64 on the edge Alpine repo; https://pkgs.alpinelinux.org/packages?name=galera&branch=edge
but no build for arm/arm64 so no good for this image because we are multi arch here! 

Definatly do-able though see here for more info https://github.com/codership/galera/
